services:
  techbridge-user:
    build: .
    image: techbridge-helprequest:latest
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/help_request_db
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
    networks:
      - techBridge
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  techBridge:
    driver: bridge
