spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/help_request_db
    username: admin
    password: admin888
  jpa:
    hibernate:
      ddl-auto: update
aws:
  s3:
    bucket-name: techbridge-s3
    region: eu-west-1
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}