spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/help_request_db
    username: admin
    password: admin888
  jpa:
    hibernate:
      ddl-auto: update
